spring.application.name=springsecOATUH2

spring.security.user.name=${SECURITY_USERNAME:eazybytes}
spring.security.user.password=${SECURITY_PASSWORD:12345}
logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:TRACE}
logging.pattern.console = ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID:Ov23li7hVP9vsATSnwKO}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET:052447809a970293900a54f9aa881746113e5bd1}

spring.security.oauth2.client.registration.facebook.client-id=${FACEBOOK_CLIENT_ID:1324986002519262}
spring.security.oauth2.client.registration.facebook.client-secret=${FACEBOOK_CLIENT_SECRET:da9913105d2b373c2a79067c635177e2}